### PR TITLE
Model Validations and Unit Testing

### PR DESCRIPTION
**Pull request by zamcham**
This pull request delivers essential improvements to the project, focusing on data reliability and testing comprehensiveness. All requirements have been met, resulting in:

- **User Model:** Added non-blank name validation and ensured PostsCounter is a non-negative integer. Unit specs for thorough testing.

- **Post Model:** Implemented non-blank and character limit (250) validation for Title. Validated CommentsCounter and optimized LikesCounter validation. Unit specs added.

### CODE REVIEW

**Review by Nemwel-Boniface — CHANGES_REQUESTED** [review]
## Hello @zamcham :wave: 

### This is a manual review

# :recycle:  Request Changes :recycle: 




- [x] As per your provided [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md), you are required to write specs for your models validations as well as the specs for the methods that are supposed to be in the models. As there exists no methods in your models, you were not able to write any specs for them.
    - However for you to pass this milestone and meet the project requirements, there must exist specs for the model methods as well. If you might have missed implementing this, kindly have a look at this link for the project requirements for [processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md) to implement all the methods listed there in your models and then write the specs for those methods.

Cheers and Happy coding! :rocket:

**Comment by zamcham** [comment]
Thank you @Nemwel-Boniface , I have added the missing methods and tests as suggested :) you can take a look now

**Review by Nemwel-Boniface — APPROVED** [review]
## Hello @zamcham :wave: 

### This is a manual review

# :heavy_check_mark:  Approved :heavy_check_mark: 




- [x] Good job making the changes that I requested. All the tests pass and are written correctly :rocket: 

image


Cheers and Happy coding! :rocket:

**Comment by bellom** [comment]
@zamcham - thank you for merging.

**Pull request merged**
